### ISSUE TITLE
Invalid Arg Type error

### ISSUE THREAD

**Issue by h-Nystrom** [Bhacaz/checkout-files#16]
Hi,
I've tried this action on two of my repositories. My new test repository is working flawless, but I keep getting this error message on my older repo do you know what the issue could be?

Run h-nystrom/checkout-files@v[2](https://github.com/h-nystrom/repo2/runs/7555074071?check_suite_focus=true#step:4:2)
  with:
    files: Plugins
    token: ***

node:internal/errors:4[6](https://github.com/h-nystrom/repo2/runs/7555074071?check_suite_focus=true#step:4:7)4
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:3[7](https://github.com/h-nystrom/repo2/runs/7555074071?check_suite_focus=true#step:4:8)1:5)
    at Function.from (node:buffer:322:9)
    at saveContent (/home/runner/work/_actions/h-nystrom/checkout-files/v2/index.js:34:32)
    at /home/runner/work/_actions/h-nystrom/checkout-files/v2/index.js:2[8](https://github.com/h-nystrom/repo2/runs/7555074071?check_suite_focus=true#step:4:9):13
    at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/h-nystrom/repo2/runs/7555074071?check_suite_focus=true#step:4:10)6:5) {
  code: 'ERR_INVALID_ARG_TYPE'

**Comment by Bhacaz** [comment]
Hi, thanks for the report.

Looking at the error, `checkout-files/v2/index.js:34:32`, it seems that [`data.content`](https://github.com/Bhacaz/checkout-files/blob/master/index.js#L34) is have no data.

* Is `Plugins` a folder and/or empty folder?
* Is `Plugins` an empty file, if a folder, does it content an empty file?

**Comment by h-Nystrom** [comment]
Ok, interesting. I have the same folder structure in my other repo:
./Plugins/PluginA/File1.h
./Plugins/PluginB/File2.h
...
I basically want to checkout all files in that folder.
Could the issue be that it doesn't find the folder in the root of my old repo?

Thanks for the help! :)

**Comment by pl4nty** [comment]
It doesn't appear to support subfolders :(
